name: Concerto Platform CI

on:
  push:
    branches:
      - 5.0-dev
      - 5.1-dev
      - github-actions

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install PHP dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.2
          version: 2.2.21

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install bower
        run: npm install -g bower

      - name: Install JS dependencies (1/2)
        run: cd ${{ github.workspace }}/src/Concerto/PanelBundle/Resources/public/angularjs && bower install --allow-root

      - name: Install JS dependencies (2/2)
        run: cd ${{ github.workspace }}/src/Concerto/TestBundle/Resources/public/angularjs && bower install --allow-root

      - name: Start MySQL service
        run: sudo service mysql start

      - name: Create MySQL test database
        run: sudo mysql -u root -e 'CREATE DATABASE concerto_test;'